/**
 * ShardFlow V1 — Canonical Error Codes
 *
 * Source of truth: docs/error-codes.md
 * Uses SCREAMING_SNAKE_CASE with <RESOURCE>_<CONDITION> or <CONTEXT>_<RESOURCE>_<CONDITION>.
 */
export const ErrorCode = {
  // Authentication Errors (401)
  AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
  INVALID_AUTH_TOKEN: 'INVALID_AUTH_TOKEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  INVALID_API_KEY: 'INVALID_API_KEY',
  API_KEY_REVOKED: 'API_KEY_REVOKED',
  API_KEY_EXPIRED: 'API_KEY_EXPIRED',

  // Authorization Errors (403)
  ACCESS_DENIED: 'ACCESS_DENIED',
  PROJECT_ACCESS_DENIED: 'PROJECT_ACCESS_DENIED',
  RESOURCE_ACCESS_DENIED: 'RESOURCE_ACCESS_DENIED',
  TENANT_ACCESS_DENIED: 'TENANT_ACCESS_DENIED',

  // Request Validation Errors (400)
  INVALID_REQUEST: 'INVALID_REQUEST',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  INVALID_FIELD: 'INVALID_FIELD',
  INVALID_FIELD_TYPE: 'INVALID_FIELD_TYPE',
  INVALID_FIELD_FORMAT: 'INVALID_FIELD_FORMAT',
  INVALID_ID: 'INVALID_ID',
  INVALID_PROJECT_ID: 'INVALID_PROJECT_ID',
  INVALID_SHARD_ID: 'INVALID_SHARD_ID',
  INVALID_TENANT_ID: 'INVALID_TENANT_ID',

  // Project Errors (404, 409)
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
  PROJECT_ALREADY_EXISTS: 'PROJECT_ALREADY_EXISTS',
  PROJECT_DISABLED: 'PROJECT_DISABLED',

  // API Key Errors (404)
  API_KEY_NOT_FOUND: 'API_KEY_NOT_FOUND',

  // Shard Errors (400, 404, 409, 502, 503)
  SHARD_NOT_FOUND: 'SHARD_NOT_FOUND',
  SHARD_ALREADY_EXISTS: 'SHARD_ALREADY_EXISTS',
  SHARD_UNAVAILABLE: 'SHARD_UNAVAILABLE',
  SHARD_DISABLED: 'SHARD_DISABLED',
  SHARD_CONNECTION_FAILED: 'SHARD_CONNECTION_FAILED',
  SHARD_CREDENTIALS_INVALID: 'SHARD_CREDENTIALS_INVALID',

  // Tenant Mapping Errors (404, 409)
  TENANT_MAPPING_NOT_FOUND: 'TENANT_MAPPING_NOT_FOUND',
  TENANT_MAPPING_ALREADY_EXISTS: 'TENANT_MAPPING_ALREADY_EXISTS',
  TENANT_MAPPING_CONFLICT: 'TENANT_MAPPING_CONFLICT',

  // Routing Errors (404, 503)
  ROUTING_CONFIG_NOT_FOUND: 'ROUTING_CONFIG_NOT_FOUND',
  ROUTING_STRATEGY_NOT_SUPPORTED: 'ROUTING_STRATEGY_NOT_SUPPORTED',
  ROUTING_FAILED: 'ROUTING_FAILED',

  // Data Plane Errors (400, 401, 403, 404, 422, 502, 503, 504)
  OPERATION_NOT_ALLOWED: 'OPERATION_NOT_ALLOWED',
  UNSUPPORTED_OPERATION: 'UNSUPPORTED_OPERATION',
  INVALID_COLLECTION: 'INVALID_COLLECTION',
  OPERATOR_NOT_ALLOWED: 'OPERATOR_NOT_ALLOWED',
  UNSUPPORTED_OPTION: 'UNSUPPORTED_OPTION',
  INVALID_OPTION: 'INVALID_OPTION',
  INVALID_LIMIT: 'INVALID_LIMIT',
  INVALID_SKIP: 'INVALID_SKIP',
  INVALID_SORT: 'INVALID_SORT',
  INVALID_PROJECTION: 'INVALID_PROJECTION',
  PROJECT_RESOLUTION_FAILED: 'PROJECT_RESOLUTION_FAILED',
  TENANT_RESOLUTION_FAILED: 'TENANT_RESOLUTION_FAILED',
  SHARD_RESOLUTION_FAILED: 'SHARD_RESOLUTION_FAILED',
  CLIENT_SHARD_SELECTION_NOT_ALLOWED: 'CLIENT_SHARD_SELECTION_NOT_ALLOWED',
  DATABASE_OPERATION_FAILED: 'DATABASE_OPERATION_FAILED',
  DATABASE_OPERATION_TIMEOUT: 'DATABASE_OPERATION_TIMEOUT',
  DATABASE_DUPLICATE_KEY: 'DATABASE_DUPLICATE_KEY',
  DATABASE_DOCUMENT_NOT_FOUND: 'DATABASE_DOCUMENT_NOT_FOUND',
  DATABASE_QUERY_INVALID: 'DATABASE_QUERY_INVALID',

  // Connection Errors (503, 504)
  CONNECTION_POOL_UNAVAILABLE: 'CONNECTION_POOL_UNAVAILABLE',
  CONNECTION_ACQUISITION_TIMEOUT: 'CONNECTION_ACQUISITION_TIMEOUT',
  CONNECTION_MANAGER_ERROR: 'CONNECTION_MANAGER_ERROR',

  // Rate Limiting & Sizing Errors (413, 429)
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  REQUEST_TOO_LARGE: 'REQUEST_TOO_LARGE',
  DOCUMENT_TOO_LARGE: 'DOCUMENT_TOO_LARGE',

  // Resource State Errors (404, 409)
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_DISABLED: 'RESOURCE_DISABLED',
  RESOURCE_STATE_CONFLICT: 'RESOURCE_STATE_CONFLICT',

  // System & External Service Errors (500, 503)
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  AUTH_PROVIDER_UNAVAILABLE: 'AUTH_PROVIDER_UNAVAILABLE',
  EMAIL_PROVIDER_UNAVAILABLE: 'EMAIL_PROVIDER_UNAVAILABLE',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
